<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerPublishDir>$(MSBuildThisFileDirectory)../docker/publish/stackexchange</DockerPublishDir>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
        <PackageReference Include="Grpc.Tools" Version="2.80.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Polly" Version="8.6.6" />
        <PackageReference Include="StackExchange.Redis">
          <Version>2.12.8</Version>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\docker\Dockerfile.stackexchange">
        <Link>Dockerfile.stackexchange</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="Protos/redis_test.proto" GrpcServices="Server" />
    </ItemGroup>

    <Target Name="PublishToDocker" AfterTargets="Build" Condition="'$(PublishToDocker)' != 'false'">
        <Exec Command="dotnet publish &quot;$(MSBuildProjectFullPath)&quot; --no-build -c $(Configuration) -o &quot;$(DockerPublishDir)&quot;" />
    </Target>

</Project>
